//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace QuoteWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public int Id { get; set; }
        [Required]
        [MinLength(3)]
        [MaxLength(20)]
        public string Name { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        public System.DateTime DateOfBirth { get; set; }
        [Required]
        public int CarYear { get; set; }
        [Required]
        public string CarMake { get; set; }
        [Required]
        public string CarModel { get; set; }

        [Required]
        public bool HasDUI { get; set; }
        [Required]
        [Range(typeof(int), "1", "500")]
        public int NoOfSpeedingTicket { get; set; }
        [Required]
        public string CoverageOrLiability { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public double TotalCost { get; set; }
    }
}
